# application ?? ?, port? ???? ??????, ??????? port? 0?? ??.
# ??? instance_id? port:0?? ?? ?? eureka ????? ??? ????? ?? ??? instance_id? ????.
server:
  port: 0  # Memo. port ?? ??

spring:
  application:
    name: my-first-service


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:}${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaulrZone: http://localhost:8761/eureka
