server:
  port: 0  # Memo. port ?? ??

spring:
  application:
    name: my-second-service


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:}${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaulrZone: http://localhost:8761/eureka

