server:
  port: 8000

#spring:
#  application:
#    name: gateway-server
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
##          uri: http://localhost:54660/
#          # Memo. ?? ???(???? ???? ???? ???? ???)?? ??
#          uri: lb://MY-FIRST-SERVICE
#
#          # Memo. ??? ????? ?? ??? '/first-service/**? ????~' ?? ??
#          predicates:
#            - Path=/first-service/**
#
#          # Memo. Global, Custom ?? ??? ???? ??
#          #       (request, response ??? ???, segment? ??? ?? ??)
#          filters:
#            - AddRequestHeader=first-request, first-request-header
#            - AddResponseHeader=first-response, first-response-header
#            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#
#        - id: second-service
##          uri: http://localhost:54726/
#          uri: lb://MY-SECOND-SERVICE
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaulrZone: http://localhost:8761/eureka

